# Generated by Django 2.2.2 on 2019-06-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20190612_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='associations',
            field=models.ManyToManyField(blank=True, to='profiles.Organization'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='awards',
            field=models.ManyToManyField(blank=True, to='profiles.Award'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='work_experiences',
            field=models.ManyToManyField(blank=True, to='profiles.WorkExperience'),
        ),
    ]
