# Generated by Django 2.2.2 on 2019-06-13 05:31

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


def convert_jurisdiction_to_arrayfield(apps, schema_editor):
    Profiles = apps.get_model('profiles', 'Profile')
    for profile in Profiles.objects.all():
        profile.jurisdiction = f"{{{profile.jurisdiction}}}"
        profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20190612_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='work_experiences',
        ),
        migrations.AddField(
            model_name='workexperience',
            name='profile',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile', verbose_name='Profile'),
            preserve_default=False,
        ),
        migrations.RunPython(convert_jurisdiction_to_arrayfield),
        migrations.AlterField(
            model_name='profile',
            name='jurisdiction',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], max_length=2), blank=True, null=True, size=None, verbose_name='Jurisdiction'),
        ),
    ]
