# Generated by Django 2.2.2 on 2019-06-13 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20190613_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissions',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile', verbose_name='Profile'),
        ),
    ]
