# Generated by Django 2.2.2 on 2019-06-06 16:51

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20190606_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='dummy-img.png', upload_to=profiles.models.get_image_path),
        ),
    ]
