# Generated by Django 2.2.2 on 2019-06-13 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20190613_0531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='associations',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='awards',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='education',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='law_school',
        ),
        migrations.AddField(
            model_name='address',
            name='profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile', verbose_name='Profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admissions',
            name='profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile', verbose_name='Profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='award',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile', verbose_name='Profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='education',
            name='profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile', verbose_name='Profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lawschool',
            name='profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile', verbose_name='Profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile', verbose_name='Profile'),
            preserve_default=False,
        ),
    ]
