# Generated by Django 2.2.2 on 2019-06-13 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20190613_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='profiles.Profile', verbose_name='Profile'),
        ),
    ]
