# Generated by Django 2.2.2 on 2019-06-27 12:16

from django.db import migrations, models
import profiles.models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_auto_20190622_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to=profiles.models.get_image_path, verbose_name='Profile Picture'),
        ),
    ]
