# Generated by Django 2.2.2 on 2019-07-01 15:09

import django.contrib.postgres.fields
from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_auto_20190627_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='law_type_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None, verbose_name='Law Type Tags'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=profiles.models.get_image_path, verbose_name='Profile Picture'),
        ),
    ]
