# Generated by Django 2.2.2 on 2019-07-02 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_auto_20190701_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='summary',
            field=models.CharField(blank=True, max_length=140, verbose_name='Summary'),
        ),
    ]
