# Generated by Django 2.2.2 on 2019-07-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_profile_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='publish_to_thb',
            field=models.BooleanField(default=False, verbose_name='Publish To THB'),
        ),
    ]
