# Generated by Django 2.2.3 on 2019-07-04 01:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_profile_publish_to_thb'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subjective_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None, verbose_name='Subjective Tags'),
        ),
    ]
