# Generated by Django 2.2.3 on 2019-07-11 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_transaction'),
        ('profiles', '0022_profile_subjective_tags'),
    ]

    operations = [
    ]
