# Generated by Django 2.2.3 on 2019-07-13 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0023_auto_20190713_0549'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='language',
            unique_together={('profile', 'name')},
        ),
    ]
