# Generated by Django 2.2.3 on 2019-07-17 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0024_auto_20190713_0558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='languages',
        ),
    ]
