# Generated by Django 2.2.3 on 2019-07-18 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0025_remove_profile_languages'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='language',
            unique_together=set(),
        ),
    ]
