# Generated by Django 2.2.3 on 2019-07-24 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0026_auto_20190718_0828'),
        ('profiles', '0023_auto_20190723_0410'),
    ]

    operations = [
    ]
