# Generated by Django 2.2.2 on 2019-07-25 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0026_auto_20190718_0828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='clients',
        ),
    ]
