# Generated by Django 2.2.3 on 2019-07-29 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0027_merge_20190724_0600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='clients',
        ),
    ]
