# Generated by Django 2.2.3 on 2019-07-31 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0028_auto_20190730_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='headline',
        ),
    ]
