# Generated by Django 2.2.3 on 2019-08-01 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0029_remove_profile_headline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='proof_receipt_requestee',
        ),
    ]
