# Generated by Django 2.2.2 on 2019-08-05 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0030_remove_transaction_proof_receipt_requestee'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
