# Generated by Django 2.2.3 on 2019-08-15 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0031_profile_full_name'),
        ('profiles', '0030_capitalisation_on_language_proficiency'),
    ]

    operations = [
    ]
