# Generated by Django 2.2.3 on 2019-08-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0032_merge_20190815_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(default='Default full name', max_length=100),
            preserve_default=False,
        ),
    ]
