# Generated by Django 2.2.3 on 2019-08-21 22:07

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0033_auto_20190815_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='license_status',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='is_confirmed',
            field=models.NullBooleanField(default=None, verbose_name='Requestee Confirmed'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='proof_receipt_requester',
            field=models.ImageField(blank=True, null=True, upload_to=profiles.models.get_image_path, verbose_name='Transaction Proof'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='value_in_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Value in USD'),
        ),
    ]
