# Generated by Django 2.2.4 on 2019-08-27 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0034_auto_20190821_2207'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
