# Generated by Django 2.2.4 on 2019-08-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0034_auto_20190821_2207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='proof_receipt_requester',
            new_name='proof_receipt',
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_proof_by_requester',
            field=models.NullBooleanField(default=None, verbose_name='Receipt added by requester'),
        ),
    ]
