# Generated by Django 2.2.6 on 2019-10-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0036_auto_20190926_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='register_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Empty profile'), (1, 'No attorney proof'), (2, 'Email not confirmed'), (3, 'Complete')], default=0),
        ),
    ]
