# Generated by Django 2.2.6 on 2019-10-23 05:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('profiles', '0037_profile_register_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
