# Generated by Django 2.2.6 on 2019-10-23 10:41

from django.db import migrations, models

import profiles.models


class Migration(migrations.Migration):
    dependencies = [
        ('profiles', '0038_profile_email_confirmed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='passport_photo',
            field=models.ImageField(blank=True, null=True, upload_to=profiles.models.get_image_path,
                                    verbose_name='Profile Picture'),
        ),
    ]
