# Generated by Django 2.2.6 on 2019-10-23 10:51

from django.db import migrations, models

import profiles.models


class Migration(migrations.Migration):
    dependencies = [
        ('profiles', '0039_profile_passport_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bar_license_photo',
            field=models.ImageField(blank=True, null=True, upload_to=profiles.models.get_image_path,
                                    verbose_name='Bar license photo'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='passport_photo',
            field=models.ImageField(blank=True, null=True, upload_to=profiles.models.get_image_path,
                                    verbose_name='Passport photo'),
        ),
    ]
