# Generated by Django 2.2.6 on 2019-10-23 11:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('profiles', '0040_auto_20191023_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='register_status',
        ),
    ]
