stages:
  - test
  - deploy

services:
  - postgres:latest

cache:
  paths:
    - ~/.cache/pip/
    - ~/.cache/pipenv/

test:
  stage: test
  image: python:latest
  variables:
    DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/postgres"
  script:
    - pipenv install --system
    - python3 manage.py test

deploy:
  stage: deploy
  image: ruby:latest
  script:
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_STAGING_API_KEY
  only:
    - master