# Generated by Django 2.2.5 on 2019-10-17 12:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sender_principal', models.NullBooleanField(choices=[(True, 'I paid them for work.'), (False, 'They paid me for work.'), (None, 'We have paid each other for work.')], default=None, verbose_name='Sender Principal')),
                ('work_description', models.TextField(max_length=500)),
                ('rating', models.CharField(choices=[('SD', 'Strongly Disagree'), ('D', 'Disagree'), ('N', 'Neutral'), ('A', 'Agree'), ('SA', 'Strongly Agree')], default='N', max_length=2, verbose_name="Requester's Review")),
                ('review', models.CharField(max_length=100)),
                ('deleted_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 10, 17, 12, 54, 54, 839223))),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL, verbose_name='Receiver')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL, verbose_name='Sender')),
            ],
            options={
                'unique_together': {('sender', 'receiver')},
            },
        ),
    ]
