# Generated by Django 2.2.4 on 2019-09-04 11:15

from django.db import migrations, models

import profiles.models


class Migration(migrations.Migration):
    dependencies = [
        ('transactions', '0002_auto_20190828_0625'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(verbose_name='What was the date of the transaction?'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='is_requester_principal',
            field=models.BooleanField(default=False, verbose_name='Did one of you pay the other?'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='proof_receipt',
            field=models.ImageField(blank=True, null=True, upload_to=profiles.models.get_image_path,
                                    verbose_name='Screenshot of wire transfer (Optional)'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='requestee_recommendation',
            field=models.TextField(blank=True, default='', verbose_name="Requestee's recommendation"),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='requestee_review',
            field=models.CharField(
                choices=[('SD', 'Strongly Disagree'), ('D', 'Disagree'), ('N', 'Neutral'), ('A', 'Agree'),
                         ('SA', 'Strongly Agree')], default='', max_length=2,
                verbose_name='Would you work with them again?'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='requester_recommendation',
            field=models.TextField(blank=True, default='', verbose_name='Write a brief recommendation'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='requester_review',
            field=models.CharField(
                choices=[('SD', 'Strongly Disagree'), ('D', 'Disagree'), ('N', 'Neutral'), ('A', 'Agree'),
                         ('SA', 'Strongly Agree')], default='', max_length=2, verbose_name="Requester's Review"),
        ),
    ]
