# Generated by Django 2.2.4 on 2019-08-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20190828_0625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_admin_approved',
            field=models.NullBooleanField(default=None, verbose_name='Approved from Admin'),
        ),
    ]
