# Generated by Django 2.2.4 on 2019-09-05 02:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('transactions', '0003_auto_20190829_1019'),
        ('transactions', '0004_auto_20190905_0122'),
    ]

    operations = [
    ]
