# Generated by Django 2.2.4 on 2019-09-09 02:23

from django.db import migrations, models

import profiles.models


class Migration(migrations.Migration):
    dependencies = [
        ('transactions', '0005_merge_20190905_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(verbose_name='Transaction Date'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='is_requester_principal',
            field=models.BooleanField(choices=[(True, 'I paid them'), (False, 'They paid me')], default=False,
                                      verbose_name='Requester Payed'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='proof_receipt',
            field=models.ImageField(blank=True, null=True, upload_to=profiles.models.get_image_path,
                                    verbose_name='Transaction Proof'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='requestee_review',
            field=models.CharField(
                choices=[('SD', 'Strongly Disagree'), ('D', 'Disagree'), ('N', 'Neutral'), ('A', 'Agree'),
                         ('SA', 'Strongly Agree')], default='N', max_length=2,
                verbose_name="Requestee's recommendation"),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='requester_recommendation',
            field=models.TextField(blank=True, default='', verbose_name="Requester's recommendation"),
        ),
    ]
