# Generated by Django 2.2.4 on 2019-09-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('transactions', '0006_auto_20190909_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='is_requester_principal',
            field=models.BooleanField(choices=[(True, 'Requester payed'), (False, 'Requestee payed')], default=False,
                                      verbose_name='Requester Payed'),
        ),
    ]
