# Generated by Django 2.2.6 on 2019-11-01 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0009_auto_20191014_0057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='requestee',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='requester',
        ),
        migrations.AddField(
            model_name='transaction',
            name='created_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='sent_to',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_sent_to', to=settings.AUTH_USER_MODEL, verbose_name='Sent to'),
            preserve_default=False,
        ),
    ]
