# Generated by Django 2.2.6 on 2019-11-08 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('transactions', '0009_auto_20191014_0057'),
    ]

    operations = [
        migrations.RenameField(model_name='Transaction',
                               old_name='requester', new_name='created_by'),
        migrations.RenameField(model_name='Transaction',
                               old_name='requestee', new_name='sent_to'),
        migrations.AlterField(
            model_name='transaction',
            name='created_by',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='transaction_created_by',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sent_to',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='transaction_sent_to',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Sent to'),
        ),
    ]
